### ISSUE TITLE
Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by ju0594** [michaelize/81online#2]
使用/81online/install.php输入相关后提交出现
`Access denied for user ''@'localhost' (using password: NO)`
如果手动创建config.inc.php设置好后，再导入数据库并用手动新建管理员，还是登陆不上去(页面跳转了下又回来了)...
感觉是不是我web环境哪里不对？
求解(＞﹏＜)

**Comment by michaelwnyc** [comment]
config.inc.php 文件权限对吗

**Comment by michaelwnyc** [comment]
检查下php的 sql.safe_mode 值是否为false 或 0.

**Comment by ju0594** [comment]
文件的权限和那项设置是这样的
`-rwxrwxrwx 1 www www  211 Apr 16 20:56 config.inc.php`
`sql.safe_mode = Off`

**Comment by michaelwnyc** [comment]
目前推测是因为mysql_connect被deprecated了，新版本有不兼容的地方。需要使用mysqli来连接。

**Comment by ju0594** [comment]
@michaelize 我也不太懂...用探针看了下：`函数mysql_connect支持状况检测结果：√`
也许不行吧...看这个项目都是三年前的,确实有点久远了(＞﹏＜)

**Comment by michaelwnyc** [comment]
最近没有太多时间更新这个项目，代码过期太久了，而且openvpn现在被封锁的比较严重。如果想使用这个平台，建议降级php来运行。或者可以访问https://tai.cool ，这是最新假设的ss平台

**Comment by zgc999** [comment]
降级到什么版本PHP？

**Comment by michaelwnyc** [comment]
尝试下 5.5.0以前的

**Comment by ju0594** [comment]
@michaelize 好的 谢谢啦。顺便说下你的SS站打不开，好像是网站设置问题。
